version: "2.1"
services:
  kafka:
      image: wurstmeister/kafka
      container_name: kafka
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_CREATE_TOPICS: contrat_out
        KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
        KAFKA_ADVERTISED_PORT: 9092
        KAFKA_LOG_RETENTION_HOURS: "168"
        KAFKA_LOG_RETENTION_BYTES: "100000000"
        KAFKA_ZOOKEEPER_CONNECT:  zookeeper:2181
  zookeeper:
    image: jeqo/apache-zookeeper:3.4.8
    container_name: zookeeper
    ports:
      - "2181:2181"
  cassandra:
    image: cassandra:3.10
    ports:
      - "9042:9042"
    expose:
      - 9060
      - 9046
    container_name: cassandra-3.10
